### ISSUE TITLE
Size of original LSTM

### ISSUE THREAD

**Issue by filljonas** [kratzert/pangeo_lstm_example#4]
Currently, I am working on a Bayesian LSTM for hydrological forecasting. Your standard LSTM implementation and associated paper (Rainfall-Runoff modelling using Long-Short-Term-Memory (LSTM) networks) is therefore an excellent source for me. However, I didn't find any information about the size of the original LSTM (hidden size, number of layers) used in the experiments described in the paper. This information would help me to gain knowledge about typical network sizes used in this domain and to conduct more "direct" comparisons. Is it possible to provide that information?

**Comment by kratzert** [comment]
Hi there,

Re 1st question: The details you are looking for are given in the first sentence of section 2.5 Experimental design.

However, I would not use the settings of this paper anymore, but refer to settings of on of our newer publications, e.g.

- Regional Modeling (also better for single basins): [https://hess.copernicus.org/articles/23/5089/2019/hess-23-5089-2019.html](https://hess.copernicus.org/articles/23/5089/2019/hess-23-5089-2019.html)
- Predictions as multiple timescales: [https://hess.copernicus.org/articles/25/2045/2021/](https://hess.copernicus.org/articles/25/2045/2021/)
- Modeling, using multiple forcings at once [https://hess.copernicus.org/preprints/hess-2020-221/](https://hess.copernicus.org/preprints/hess-2020-221/)

Furthermore, I would advice you to use our Python library [neuralHydrology](https://github.com/neuralhydrology/neuralhydrology), which will allow you to train any of the models/settings presented in the papers.
